name: Test

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pipenv
      - run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --system --deploy --ignore-pipfile --dev
      - run: flake8 .
      - run: mypy .
      - run: pytest
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/postgres
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost/test
