name: Test

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      server-db:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 3s
        healthcheck:
          test: pg_isready -U postgres
          interval: 3s
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --system --deploy --ignore-pipfile --dev
      - run: flake8 .
      - run: mypy --strict .
        continue-on-error: true
      - run: pytest
        env:
          DATABASE_URL: postgres://postgres:postgres@server-db/postgres
          TEST_DATABASE_URL: postgres://postgres:postgres@server-db/postgres
